[project]
name = "pg-rnn"
version = "1.0"
description = "BPE RNN trained on Paul Grahams Essays"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "datasets>=3.6.0",
  "tiktoken>=0.9.0",
  "torch>=2.7.1",
  "torchaudio>=2.7.1",
  "torchvision>=0.22.1",
]
